-- MySQL Script generated by MySQL Workbench
-- 11/30/16 23:54:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema balcao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema balcao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `balcao` DEFAULT CHARACTER SET utf8 ;
USE `balcao` ;

-- -----------------------------------------------------
-- Table `balcao`.`tipo_usu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`tipo_usu` (
  `cod_tipo_usu` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_usu` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_tipo_usu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`usuarios` (
  `cod_usu` INT NOT NULL AUTO_INCREMENT,
  `cpf_usu` VARCHAR(11) NOT NULL,
  `nome_usu` VARCHAR(45) NOT NULL,
  `login_usu` VARCHAR(10) NOT NULL,
  `senha_usu` VARCHAR(10) NOT NULL,
  `tipo_usu_cod_tipo_usu` INT NOT NULL,
  PRIMARY KEY (`cod_usu`),
  INDEX `fk_usuarios_tipo_usu1_idx` (`tipo_usu_cod_tipo_usu` ASC),
  CONSTRAINT `fk_usuarios_tipo_usu1`
    FOREIGN KEY (`tipo_usu_cod_tipo_usu`)
    REFERENCES `balcao`.`tipo_usu` (`cod_tipo_usu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`marca` (
  `cod_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`tamanho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`tamanho` (
  `cod_tam` INT NOT NULL AUTO_INCREMENT,
  `nome_tam` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_tam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`vendas` (
  `cod_vendas` INT NOT NULL AUTO_INCREMENT,
  `data_vendas` DATE NOT NULL,
  `subTotal` DOUBLE NOT NULL,
  `total` DOUBLE NOT NULL,
  `cpf` VARCHAR(25) NULL,
  PRIMARY KEY (`cod_vendas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`tipo_pro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`tipo_pro` (
  `cod_tipo_pro` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo_pro` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_tipo_pro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`carrinho` (
  `nome_car_pro` VARCHAR(15) NOT NULL,
  `preco_car_pro` DOUBLE NOT NULL,
  `qtd_car` INT NOT NULL,
  `subTotal_car` DOUBLE NOT NULL,
  `total_car` DOUBLE NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`produto` (
  `cod_pro` INT NOT NULL AUTO_INCREMENT,
  `nome_pro` VARCHAR(45) NOT NULL,
  `preco_pro` DOUBLE NOT NULL,
  `estoque_pro` VARCHAR(45) NOT NULL,
  `tipo_pro_cod_tipo_pro` INT NOT NULL,
  `marca_cod_marca` INT NOT NULL,
  `tamanho_cod_tam` INT NOT NULL,
  PRIMARY KEY (`cod_pro`),
  INDEX `fk_produto_tipo_pro1_idx` (`tipo_pro_cod_tipo_pro` ASC),
  INDEX `fk_produto_marca1_idx` (`marca_cod_marca` ASC),
  INDEX `fk_produto_tamanho1_idx` (`tamanho_cod_tam` ASC),
  CONSTRAINT `fk_produto_tipo_pro1`
    FOREIGN KEY (`tipo_pro_cod_tipo_pro`)
    REFERENCES `balcao`.`tipo_pro` (`cod_tipo_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_marca1`
    FOREIGN KEY (`marca_cod_marca`)
    REFERENCES `balcao`.`marca` (`cod_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_tamanho1`
    FOREIGN KEY (`tamanho_cod_tam`)
    REFERENCES `balcao`.`tamanho` (`cod_tam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `balcao`.`vendas_has_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `balcao`.`vendas_has_produto` (
  `vendas_cod_vendas` INT NOT NULL,
  `produto_cod_pro` INT NOT NULL,
  `qtd_pro` INT NOT NULL,
  PRIMARY KEY (`vendas_cod_vendas`, `produto_cod_pro`),
  INDEX `fk_vendas_has_produto_produto1_idx` (`produto_cod_pro` ASC),
  INDEX `fk_vendas_has_produto_vendas1_idx` (`vendas_cod_vendas` ASC),
  CONSTRAINT `fk_vendas_has_produto_vendas1`
    FOREIGN KEY (`vendas_cod_vendas`)
    REFERENCES `balcao`.`vendas` (`cod_vendas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendas_has_produto_produto1`
    FOREIGN KEY (`produto_cod_pro`)
    REFERENCES `balcao`.`produto` (`cod_pro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
